DEVELOPER_WEIGHT = .6
PUBLISHER_WEIGHT = .5
PLATFORM_WEIGHT = 1
REQUIRED_AGE_WEIGHT = .2
CATEGORY_WEIGHT = .7
GENRE_WEIGHT = .9

WEIGHT_SUM = (
  DEVELOPER_WEIGHT + 
  PUBLISHER_WEIGHT + 
  PLATFORM_WEIGHT + 
  REQUIRED_AGE_WEIGHT +
  CATEGORY_WEIGHT +
  GENRE_WEIGHT)